### ISSUE TITLE
mappings cannot target metadata

### ISSUE THREAD

**Issue by lukebond** [influxdata/sinker#9]
consider the following `ResourceSync`, taken from our current system:

```yaml
apiVersion: sinker.influxdata.io/v1alpha1
kind: ResourceSync
metadata:
  name: cluster-0001-kustomization-status
  namespace: customer-0001
spec:
  mappings:
  - fromFieldPath: status
    toFieldPath: spec
  - fromFieldPath: metadata.labels
    toFieldPath: metadata.labels
  source:
    cluster:
      kubeConfig:
        secretRef:
          key: value
          name: cluster-0001-kubeconfig
      namespace: iox
    resourceRef:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: iox-manifests
  target:
    resourceRef:
      apiVersion: tubernetes.influxdata.io/v1beta2
      kind: FluxcdKustomizationStatus
      name: iox-manifests
```

note that it has a mapping to copy the labels from source to target.

this doesn't work because on this line it is `root.data` that is passed into the `set_field_path` function: https://github.com/influxdata/sinker/blob/main/src/controller.rs#L168

`root.data` contains `{ spec: {...}, status: {...} }`, the metadata is kept outside of the `data` object.
